# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "expenses", :force => true do |t|
    t.column "name", :string
    t.column "datum", :date
    t.column "netto", :float
    t.column "brutto", :float
    t.column "mwst", :float
    t.column "art", :string
    t.column "bezahlt", :boolean
    t.column "abgerechnet", :boolean, :default => false
    t.column "eintragsdatum", :date
    t.column "geloescht", :boolean, :default => false
    t.column "user_id", :integer
    t.column "statement_id", :integer
  end

  create_table "gains", :force => true do |t|
    t.column "name", :string
    t.column "datum", :date
    t.column "netto", :float
    t.column "brutto", :float
    t.column "mwst", :float
    t.column "bezahlt", :boolean
    t.column "abgerechnet", :boolean, :default => false
    t.column "eintragsdatum", :date
    t.column "geloescht", :boolean, :default => false
    t.column "user_id", :integer
    t.column "statement_id", :integer
  end

  create_table "statements", :force => true do |t|
    t.column "name", :string
    t.column "erstellungsdatum", :date
  end

  create_table "users", :force => true do |t|
    t.column "name", :string
    t.column "login", :string
    t.column "email", :string
    t.column "crypted_password", :string, :limit => 40
    t.column "salt", :string, :limit => 40
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "remember_token", :string
    t.column "remember_token_expires_at", :datetime
  end

end
